#! /bin/sh

chosen=$(printf "Apagar\nReiniciar\nCerrar Sesion" | rofi -dmenu -i -theme $HOME/.config/rofi/material/material.rasi)

case "$chosen" in
	"Apagar") systemctl poweroff ;;
	"Reiniciar") systemctl reboot ;;
	"Cerrar Sesion") bspc quit ;;
	*)exit 1;;
esac
